services:
  postgres:
    image: postgres:18-alpine
    container_name: media_db
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: ChangeMe123!
      POSTGRES_DB: cmsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: media_cache
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: media_search
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    volumes:
      - os_data:/usr/share/opensearch/data

  cms-service:
    build:
      context: ./cms
      dockerfile: Dockerfile
    container_name: cms_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cmsdb
      DB_USER: demouser
      DB_PASSWORD: ChangeMe123!
      OS_ENDPOINT: http://opensearch:9200
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      S3_BUCKET: ${S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_CLOUDFRONT_DOMAIN: ${AWS_CLOUDFRONT_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      - postgres
      - opensearch

  discovery-service:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery_api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      OS_ENDPOINT: http://opensearch:9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_REGION: ${AWS_REGION}
    depends_on:
      - redis
      - opensearch
      - cms-service

volumes:
  postgres_data:
  os_data:
